name: "testing capture"
on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: HadiAlizade77/github-screenshot-action@development
